---
title: "Lab 8 Part 2"
author: "Justine Lang"
date: "2023-03-02"
output: html_document
---

```{r setup, echo = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(lubridate)
library(tsibble)
library(feasts)
library(slider)
```

## Read in the data

```{r}
toolik <- read_csv(here('data/toolikweather.csv'))

toolik_ts <- toolik %>% 
  mutate(date = mdy(date)) %>%
  as_tsibble(key = NULL, index = date)

ggplot(data = toolik_ts, aes(x = date, y = mean_airtemp)) +
  geom_line() +
  labs(x = 'Date', y = 'Mean daily air temp (Celcius)\nat Toolik Station')
```


## Use `index_by` to aggregate time series by different increments

```{r}
toolik_month <- toolik_ts %>% 
  index_by(yr_mo = ~yearmonth(.)) %>% 
  summarize(monthly_mean_temp = mean(mean_airtemp, na.rm = TRUE))

ggplot(toolik_month, aes(x = yr_mo, y = monthly_mean_temp)) +
  geom_line()

toolik_month %>% 
  ggplot(aes(x = year(yr_mo), y = monthly_mean_temp)) +
  geom_line() +
  facet_wrap(~ month(yr_mo, label = TRUE)) +
  labs(x = 'Year', y = 'Annual mean air temp (Celcius)',
       title = 'Toolik Station mean annual air temperature',
       subtitle = '1988-2018',
       captions = 'Source Shaver, G. 2019. A multi-year daily weather file 
       for the Toolik Field Station at Toolik Lake, AK, starting 1988 to
       present. Ver. 4. Environmental Data Initiative.')
```

### Group by other increments in `index_by`?

```{r}
toolik_annual <- toolik_ts %>% 
  index_by(yearly = ~year(.)) %>% 
  summarize(annual_airtemp = mean(mean_airtemp, na.rm = TRUE))

ggplot(toolik_annual, aes(x = yearly, y = annual_airtemp)) +
  geom_line()

toolik_weekly <- toolik_ts %>% 
  index_by(weekly = ~yearweek(.)) %>% 
  summarize(weekly_airtemp = mean(mean_airtemp, na.rm = TRUE))

ggplot(toolik_weekly, aes(x = weekly, y = weekly_airtemp)) +
  geom_line()
```


## Use filter_index() to grab different data/time combinations

```{r}
toolik_ts %>% 
  filter_index('2000-06' ~ '2001-10')

toolik_ts %>% 
  filter_index('2006-04-10' ~ '2006-05-15')

toolik_ts %>% 
  filter_index('2017-12-20' ~ .)
```


## Let's explore seasonality

```{r}
toolik_ts %>% 
  filter_index('2014' ~ .) %>%
  feasts::gg_season(y = mean_airtemp)

toolik_month %>% 
  gg_season(y = monthly_mean_temp) +
  theme_minimal() +
  labs(x = 'year', y = 'Mean monthly air temperature (Celcius)',
       title = 'Toolik Station air temperature')
```


## Seasonal subseries plots

```{r}
toolik_month %>% 
  gg_subseries(y = monthly_mean_temp)
```


## Moving averages in time series

Let's make a test vector to try it out

```{r}
set.seed(2023)
test <- rnorm(100, mean = 40, sd = 10)
```

```{r}
w05 <- as.numeric(slide(test, mean, .before = 2, .after = 2))

w11 <- as.numeric(slide(test, mean, .before = 5, .after = 5))

w19 <- as.numeric(slide(test, mean, .before = 9, .after = 9))

combo <- data_frame(time = seq(1:100), test, w05, w11, w19) %>% 
  pivot_longer(names_to = 'series', values_to = 'value', -time)

ggplot(data = combo) +
  geom_line(aes(x = time, y = value, color = series)) +
  scale_color_manual(values = c('grey70', 'red', 'orange', 'purple')) +
  theme_minimal()
```

```{r}
roll_toolik_15 <- toolik_ts %>% 
  mutate(ma_15d = as.numeric(slide(toolik_ts$mean_airtemp, mean, 
                                   .before = 7, .after = 7)))

roll_toolik_61 <- toolik_ts %>% 
  mutate(ma_61d = as.numeric(slide(toolik_ts$mean_airtemp, mean, 
                                   .before = 30, .after = 30)))


ggplot() +
  geom_line(data = toolik_ts, aes(x = date, y = mean_airtemp), 
            size = 0.2, color = "gray") +
  geom_line(data = roll_toolik_15, aes(x = date, y = ma_15d), 
            color = "orange") +
  geom_line(data = roll_toolik_61, aes(x = date, y = ma_61d), 
            color = "blue") +
  theme_minimal()
```


### Autocorrelation function

```{r}
toolik_ts %>% 
  ACF(mean_airtemp) %>% 
  autoplot()

toolik_month %>% 
  ACF(monthly_mean_temp) %>% 
  autoplot()
```


## Decomposition

```{r}
toolik_dec <- toolik_month %>% 
  model(STL(monthly_mean_temp ~ season(window = Inf)))

components(toolik_dec) %>% 
  autoplot()
```









