---
title: "Lab 8 Part 1"
author: "Justine Lang"
date: "2023-03-02"
output: html_document
---

```{r setup, echo = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(spatstat)
library(terra)
library(tmap)
library(sf)
```

## Read in red tree vole data

```{r}
voles_sf <- read_sf(dsn = here('redtreevoledata'),
                    layer = 'ds033') %>% 
  janitor::clean_names() %>% 
  select(county) %>% 
  filter(county == 'HUM') %>% 
  st_transform(crs = 32610)

plot(voles_sf)
```


## Get Humboldt County outline

```{r}
humboldt_sf <- read_sf(here('redtreevoledata',
                            'california_county_shape_file.shp')) %>% 
  janitor::clean_names() %>% 
  filter(name %in% 'Humboldt') %>% 
  select(name) %>% 
  st_set_crs(4326) %>% 
  st_transform(32610)

# st_crs(humboldt_sf)
```


## Plot the data and the county

```{r}
ggplot() +
  geom_sf(data = humboldt_sf, 
          color = 'darkorchid',
          fill = 'darkorchid4',
          size = 1) +
  geom_sf(data = voles_sf,
          color = 'orange',
          alpha = .7,
          size = 2) +
  theme_void()
```


## Convert 'sf' objects to 'spatstat' objects

```{r}
### Convert voles observations to spatial point pattern

voles_ppp <- as.ppp(voles_sf)

### Convert county to owin object

humboldt_win <- as.owin(humboldt_sf)

### Combine together into a point pattern object (points = window)

voles_full <- ppp(voles_ppp$x, voles_ppp$y, window = humboldt_win)

plot(voles_full)
```


## Make a kernel density plot

```{r}
voles_density <- density(voles_full, sigma = 5000)

plot(voles_density)
```


### Map it in tmap

```{r}
### Convert density object to a raster

voles_r <- rast(voles_density)
# st_crs(voles_r)
crs(voles_r) <- crs(voles_sf)

### Now plot it

tmap_mode('view')
tm_shape(voles_r) +
  tm_raster(midpoint = NA, palette = 'Reds', legend.show = FALSE)
```


## Let's statistically analyze with a G function

```{r}
### Make a sequence of distances over which we'll calculate G(r)

r_vec <- seq(0, 10000, by = 100)

gfunction <- envelope(voles_full, fun = Gest, r = r_vec,
                      nsim = 100)

gfunction_long <- gfunction %>% 
  as.data.frame() %>% 
  pivot_longer(names_to = 'model', values_to = 'g_val',
               cols = obs:hi)

ggplot(data = gfunction_long, aes(x = r, y = g_val)) +
  geom_line(aes(color = model, group = model)) +
  theme_minimal() +
  labs(x = 'radius (m)', y = 'G(r)')
```


## Let's try an L function

```{r}
r_vec2 <- seq(0, 80000, by = 5000)

lfunction <- envelope(voles_full, fun = Lest, r = r_vec2,
                      nsim = 10) 
```

```{r}
lfunction_long <- lfunction %>% 
  as.data.frame() %>% 
  pivot_longer(cols = obs:hi, 
               names_to = 'model', values_to = 'l')

ggplot(data = lfunction_long,
       aes(x = r, y = l)) +
  geom_line(aes(color = model, group = model)) +
  theme_minimal() +
  labs(x = 'radius (m)', y = 'L(r)')
```









